from langchain_core.messages import HumanMessage, SystemMessage
from app.core.llm import create_llm




# Create instance of LLM
llm = create_llm()


async def basic_response_agent(context_payload: dict):
    """
     this function is a basic response agent that uses a LLM to generate a response to a task description.
     
     Args:
         task_description (str): The description of the task to be completed.
         
     Returns:
         str: The response generated by the LLM.
    """

    try:

        task_desc = context_payload.get('task_description', 'N/A')
        doc_subject = context_payload.get('document_subject', 'N/A')
        doc_summary = context_payload.get('document_summary', 'N/A')
        doc_intent = context_payload.get('document_intent', 'N/A')
        doc_facts = "\n- ".join(context_payload.get('document_facts', []))

        system_prompt = """
        Eres un asistente de sistema para un software de gestión documental. 
        Tu única función es redactar una nota breve, formal y contextual de cierre para una tarea completada. 

        Reglas de redacción:
        - Usa siempre voz pasiva o tercera persona.  
        - El texto debe ser conciso, directo y formal.  
        - No incluyas saludos, introducciones ni explicaciones adicionales.  
        - La nota debe relacionar explícitamente la tarea realizada con el contexto del expediente.  
        - La extensión máxima es de 1 a 2 oraciones.  
        - Evita repetir literalmente el contexto: resume de forma precisa.  
        """

        user_prompt = f"""
        **Contexto del Expediente:**
        - Asunto: {doc_subject}
        - Resumen: {doc_summary}
        - Intención del Documento: {doc_intent}
        - Hechos Clave:
        - {doc_facts}

        **Tarea Completada:**
        {task_desc}

        **Instrucción:**
        Redacta la nota de cierre de la tarea finalizada basándote únicamente en la información anterior. 
        La respuesta debe ser una sola nota breve que describa formalmente la acción completada en relación con el expediente.
        """


        # Creamos el prompt de LangChain
        prompt = [
            SystemMessage(content=system_prompt),
            HumanMessage(content=user_prompt)
        ]

        # Usamos el método .astream() del modelo de LangChain para obtener un generador asíncrono
        async for chunk in llm.astream(prompt):
            # Cada chunk es un objeto de mensaje, extraemos su contenido de texto
            yield chunk.content

    except Exception as e:
        error_message = f"[ERROR: No se pudo contactar al asistente de IA. Razón: {str(e)}]"
        print(error_message)
        yield error_message
    