from langchain_core.messages import HumanMessage, SystemMessage
from app.core.llm import create_llm




# Create instance of LLM
llm = create_llm()


async def basic_response_agent(task_description: str):
    """
     this function is a basic response agent that uses a LLM to generate a response to a task description.
     
     Args:
         task_description (str): The description of the task to be completed.
         
     Returns:
         str: The response generated by the LLM.
    """

    try:
        # Creamos el prompt de LangChain
        prompt = [
            SystemMessage(
                content="""
                Actúa como un asistente integrado en un software de gestión documental. 
                Tu única función es redactar una nota breve y formal de cierre para una tarea completada.  

                Reglas:
                - Usa voz pasiva o tercera persona.  
                - El texto debe ser conciso, directo y formal.  
                - No incluyas saludos, introducciones ni explicaciones.  
                - La nota debe reflejar explícitamente la tarea realizada, mencionando el documento, acción o proceso asociado.  
                - Extensión máxima: 1 a 2 oraciones.  

                Ejemplo de estilo esperado:
                - "El contrato fue revisado, validado y archivado en la carpeta correspondiente."  
                - "La solicitud de acceso fue registrada, tramitada y cerrada en el sistema."  
                - "El informe financiero quedó aprobado y vinculado al expediente institucional."
                """            
            ),
            HumanMessage(content=f"La tarea completada es: '{task_description}'.")
        ]

        # Usamos el método .astream() del modelo de LangChain para obtener un generador asíncrono
        async for chunk in llm.astream(prompt):
            # Cada chunk es un objeto de mensaje, extraemos su contenido de texto
            yield chunk.content

    except Exception as e:
        error_message = f"[ERROR: No se pudo contactar al asistente de IA. Razón: {str(e)}]"
        print(error_message)
        yield error_message
    